### ISSUE TITLE
Use a separate config file for settings

### ISSUE THREAD

**Issue by surak** [aceisace/E-Paper-Calendar-with-iCal-sync-and-live-weather#11]
This way, I won't push my key by mistake here :-)

**Comment by aceisace** [comment]
I've merged your pull request. 
Yes, it's a good idea to have a seperate configuration file. 

Thanks for contributing and improving the script :)

**Comment by aceisace** [comment]
I'm closing this issue for now. If you think that this issue should remain open, please let me know.
