### ISSUE TITLE
Typo in file name

### ISSUE THREAD

**Issue by surak** [aceisace/E-Paper-Calendar-with-iCal-sync-and-live-weather#16]
Separator is written seperator in calendar/other/en

**Comment by surak** [comment]
And the January month bitmap says "Janruary"

**Comment by aceisace** [comment]
@surak 
OK, the typos have been fixed. Could you please confirm this? Thanks

**Comment by surak** [comment]
I just tested the stable(beta).py - it still calls seperator FYI

**Comment by aceisace** [comment]
> Separator is written seperator in calendar/other/en

It's possible I misunderstood something, but I did change seperator to separator on my repo:
<img src="https://user-images.githubusercontent.com/29558518/50700162-1eb03700-104a-11e9-9f96-e65f74840c9f.png" width="500">

**Comment by aceisace** [comment]
@surak 
OK, I've fixed the typo in the stable(beta).py as well. Are there any more typos which need fixing?

**Comment by aceisace** [comment]
@surak 
> And the January month bitmap says "Janruary"

Is it fixed now?

**Comment by surak** [comment]
Sorry, back to work, didn't have any time anymore. If there's something else, I will reopen this one. Meanwhile, I close it!
