### ISSUE TITLE
No module named ics

### ISSUE THREAD

**Issue by surak** [aceisace/E-Paper-Calendar-with-iCal-sync-and-live-weather#17]
The new version reads ics files as well (I was trying to do so as well).

However, it's not clear which ics version you are using (there are many of those).

I haven't found it on the documentation, either.

**Comment by aceisace** [comment]
@surak 
OK, I've added a new page [Libraries and their versions](https://github.com/aceisace/E-Paper-Calendar-with-iCal-sync-and-live-weather/wiki/Libraries-and-their-versions) which includes the libraries and their versions. 

By the way, has the issue with 'No module named ics' been fixed?
