### ISSUE TITLE
Remove hardcoded directory

### ISSUE THREAD

**Issue by surak** [aceisace/E-Paper-Calendar-with-iCal-sync-and-live-weather#19]
Since the directory cloned is "E-Paper-Calendar-with-iCal-sync-and-live-weather", it makes no sense for it to expect this to be at "/home/pi/E-Paper-Master".

One can refer to files from his own directory and relative paths.

**Comment by aceisace** [comment]
You do have a point. Could you provide a suitable suggestion then? Thanks

**Comment by aceisace** [comment]
For now, I think I'll leave it as it is. Otherwise things might get a bit overly complicated. In the next release, I'll try doing something about it. 

I'll be closing this issue for now. If you need to re-open it, please feel free to do so.

**Comment by aceisace** [comment]
@surak 
I've implemented the relative-path feature and removed the hardcoded directory with the new release.

**Comment by surak** [comment]
Cool! I have to merge your stuff! Thanks!
