### ISSUE TITLE
Error after installing the software

### ISSUE THREAD

**Issue by multimedial** [aceisace/E-Paper-Calendar-with-iCal-sync-and-live-weather#23]
RPI zero on Jessie Lite 

The main program complains about missing python-numpy package after installation - did I do something wrong? I ran the script from the repo page: 

```
...
The install was successful
The programm is set to start at every boot.
Please enter your details in the file settings.py.
If this file is not modified, the programm will not start
To modify the settings file, enter:
nano /home/pi/E-Paper-Master/Calendar/settings.py
You can test if the programm works by typing:
python3.5 /home/pi/E-Paper-Master/Calendar/E-Paper.py
pi@raspberrypi:~ $ python3 E-Paper-Master/Calendar/E-Paper.py
Please install numpy with: sudo apt-get install python-numpy
Traceback (most recent call last):
  File "E-Paper-Master/Calendar/E-Paper.py", line 44, in <module>
    import epd7in5b
  File "/home/pi/E-Paper-Master/Calendar/epd7in5b.py", line 1, in <module>
    import epdif
  File "/home/pi/E-Paper-Master/Calendar/epdif.py", line 12, in <module>
    SPI = spidev.SpiDev(0, 0)
FileNotFoundError: [Errno 2] No such file or directory
pi@raspberrypi:~ $ sudo apt-get install python-numpy
Reading package lists... Done
Building dependency tree
Reading state information... Done
python-numpy is already the newest version (1:1.12.1-3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
pi@raspberrypi:~ $
```

**Comment by multimedial** [comment]
That's ok, just wanted to know if I had missed anything.-------- Originalnachricht --------Betreff: Re: [aceisace/E-Paper-Calendar-with-iCal-sync-and-live-weather] Error after installing the software (#23)Von: Ace An: aceisace/E-Paper-Calendar-with-iCal-sync-and-live-weather Cc: multimedial ,Mention @multimedial
Hi. thanks for pointing this out. I'll look into this asap and will fix this. As soon as I find out the cause, I'll let you know.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/aceisace/E-Paper-Calendar-with-iCal-sync-and-live-weather","title":"aceisace/E-Paper-Calendar-with-iCal-sync-and-live-weather","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/aceisace/E-Paper-Calendar-with-iCal-sync-and-live-weather"}},"updates":{"snippets":[{"icon":"PERSON","message":"@aceisace in #23: @multimedial \r\nHi. thanks for pointing this out. I'll look into this asap and will fix this. As soon as I find out the cause, I'll let you know.\r\n"}],"action":{"name":"View Issue","url":"https://github.com/aceisace/E-Paper-Calendar-with-iCal-sync-and-live-weather/issues/23#issuecomment-472061888"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/aceisace/E-Paper-Calendar-with-iCal-sync-and-live-weather/issues/23#issuecomment-472061888",
"url": "https://github.com/aceisace/E-Paper-Calendar-with-iCal-sync-and-live-weather/issues/23#issuecomment-472061888",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by aceisace** [comment]
@multimedial 
You didn't miss anything. It was a bug in the installer that caused this type of error. Basically, it should have been `sudo apt-get install python3-numpy`. I've just now fixed all bugs in the installer I could find by testing it myself on Raspbain Stretch Lite. If you select the update or install option in the installer now, it should work as expected.

If you find any more bugs, feel free to report them here. Thanks in advance.

**Comment by multimedial** [comment]
Will check. Thanks for your work!

  Ace <notifications@github.com> hat am 12. März 2019 um 19:34 geschrieben:
 
 
 @multimedial You didn't miss anything. It was a bug in the installer that caused this type of error. Basically, it should have been sudo apt-get install python3-numpy. I've just now fixed all bugs in the installer I could find by testing it myself on Raspbain Stretch Lite. If you select the update or install option in the installer now, it should work as expected. 
 If you find any more bugs, feel free to report them here. Thanks in advance.

**Comment by multimedial** [comment]
Sorry, there is still an issue...

`The install was successful
The programm is set to start at every boot.
Please enter your details in the file settings.py.
If this file is not modified, the programm will not start
To modify the settings file, enter:
nano /home/pi/E-Paper-Master/Calendar/settings.py
You can test if the programm works by typing:
python3.5 /home/pi/E-Paper-Master/Calendar/E-Paper.py
pi@raspberrypi:~ $ cd E-Paper-Master/
pi@raspberrypi:~/E-Paper-Master $ cd Calendar/
pi@raspberrypi:~/E-Paper-Master/Calendar $ python3 E-Paper.py
Traceback (most recent call last):
  File "E-Paper.py", line 44, in <module>
    import epd7in5b
  File "/home/pi/E-Paper-Master/Calendar/epd7in5b.py", line 1, in <module>
    import epdif
  File "/home/pi/E-Paper-Master/Calendar/epdif.py", line 12, in <module>
    SPI = spidev.SpiDev(0, 0)
FileNotFoundError: [Errno 2] No such file or directory
pi@raspberrypi:~/E-Paper-Master/Calendar $ sudo pip3 install spidev
Requirement already satisfied: spidev in /usr/lib/python3/dist-packages
pi@raspberrypi:~/E-Paper-Master/Calendar $`

**Comment by multimedial** [comment]
Sorry, there seems still to be an issue...

`
The install was successful
The programm is set to start at every boot.
Please enter your details in the file settings.py.
If this file is not modified, the programm will not start
To modify the settings file, enter:
nano /home/pi/E-Paper-Master/Calendar/settings.py
You can test if the programm works by typing:
python3.5 /home/pi/E-Paper-Master/Calendar/E-Paper.py
pi@raspberrypi:~ $ cd E-Paper-Master/
pi@raspberrypi:~/E-Paper-Master $ cd Calendar/
pi@raspberrypi:~/E-Paper-Master/Calendar $ python3 E-Paper.py
Traceback (most recent call last):
  File "E-Paper.py", line 44, in <module>
    import epd7in5b
  File "/home/pi/E-Paper-Master/Calendar/epd7in5b.py", line 1, in <module>
    import epdif
  File "/home/pi/E-Paper-Master/Calendar/epdif.py", line 12, in <module>
    SPI = spidev.SpiDev(0, 0)
FileNotFoundError: [Errno 2] No such file or directory
pi@raspberrypi:~/E-Paper-Master/Calendar $ sudo pip3 install spidev
Requirement already satisfied: spidev in /usr/lib/python3/dist-packages
pi@raspberrypi:~/E-Paper-Master/Calendar $

`

**Comment by multimedial** [comment]
I'd like to point out however that I haven't adapted the settings.py file just yet...

**Comment by multimedial** [comment]
Sorry, this isn't an issue any more, I had forgotten to install all libraries for the paper as pointed out py Waveshare.

**Comment by aceisace** [comment]
@multimedial 
I'm glad you could fix the issue yourself. Normally, this software is independet form waveshare so conflicts of that sort should not even exist.
I think in your case, the error:
```
SPI = spidev.SpiDev(0, 0)
FileNotFoundError: [Errno 2] No such file or directory
```
is caused due to the SPI not being activated. For reference purposes, I'll write the fix here anyway:
`sudo sed -i s/#dtparam=spi=on/dtparam=spi=on/ /boot/config.txt`
Running the above command will activate the SPI on the Raspberry and the problem should be fixed.
