### ISSUE TITLE
Incorrect url in Installer

### ISSUE THREAD

**Issue by surak** [aceisace/E-Paper-Calendar-with-iCal-sync-and-live-weather#3]
curl -sSL https://github.com/aceisace/E-Paper-Calendar-with-iCal-sync-and-live-weather/blob/master/Installer-with-debug |bash
bash: line 7: syntax error near unexpected token `newline'
bash: line 7: `<!DOCTYPE html>'
curl: (23) Failed writing body (960 != 1370)

**Comment by aceisace** [comment]
@surak 
Thanks for pointing the bug out. I‘ll check the installer again and will let you know as soon as it‘s been fixed. Does the normal Installer (without debug) also show the same error?

**Comment by aceisace** [comment]
@surak 
I've just tested the Installer _without_ debug. It seems to work just fine actually (see attached picture)

This was tested just now on a Raspberry Pi Zero W running Raspbian Stretch from June 2018. 
The command from the README page 
(curl -sSL https://raw.githubusercontent.com/aceisace/Raspberry-Pi-Google-Calendar-with-E-Paper-display/master/Packages-installer | bash) 
was executed in the terminal.

Could you provide more details on how you tried to set this up?

![pi-zero-install-successful](https://user-images.githubusercontent.com/29558518/45932863-7f2bd480-bf83-11e8-8a11-5b683761f239.png)

**Comment by aceisace** [comment]
@surak 
Alright, I've just fixed the problem involving the installer with debug. The problem was that in the README file, the link pointed to the file in html format though it should have been the plain text version. Thanks for pointing that out. Both Installers are fixed now. 

Please leave a feedback if it works now.

**Comment by aceisace** [comment]
I‘ll be closing this issue now.
