### ISSUE TITLE
Support for 2-Colour E-Paper Displays 

### ISSUE THREAD

**Issue by startedfromtheb0ttom** [aceisace/E-Paper-Calendar-with-iCal-sync-and-live-weather#4]
Hello

In the pictures some of the writing is red, but my E-Ink Display can not display this color. It can only show black. How can I change the corresponding color icons to black so that they are clearly visible on the display

**Comment by aceisace** [comment]
@startedfromtheb0ttom 
If I've understood correctly, you're probably using the waveshare 7.5" 2-Colour Display, which does not support red. 
You did mention 'clearly visible' in your comment. Does that mean that the red parts are displayed in a different manner? Could you please post a picture of the display to show the issue?

The best and most permanent fix I can think of would be to reduce the colours of the icons from 3 (black, white & red) to 2 colours (black and white). I'll try to figure out something regarding that (maybe creating a python 'converter' or manually convert the icons to just 2 colours with GIMP 2).

**Comment by startedfromtheb0ttom** [comment]
I use this 7,5" Waveshare E-Ink Display (https://www.waveshare.com/wiki/7.5inch_e-Paper_HAT). It's not the 3 Color Version. The red icons are not clearly visible on the screen from a distance
![img_2103](https://user-images.githubusercontent.com/42494071/45943076-360c6c80-bfe5-11e8-8173-d4fd59a86ad5.JPG)
![img_2104](https://user-images.githubusercontent.com/42494071/45943077-360c6c80-bfe5-11e8-92ec-048a5441d768.JPG)
![img_2105](https://user-images.githubusercontent.com/42494071/45943078-360c6c80-bfe5-11e8-8d2b-01a779f53bfe.JPG)

**Comment by aceisace** [comment]
@startedfromtheb0ttom 

Although this software wasn't originally intended to be used with the 2-colour E-Paper Display, I'm going to add full support for the 2-colour version soon. 

For now, I have a 'quick fix' which will allow you to use the software on the 2-colour E-Paper Display. I have tested it and confirm it works:
<img src="https://user-images.githubusercontent.com/29558518/46045487-25134680-c11e-11e8-96de-ee7ed57ac766.png" width="400">

### Usage; 
**`curl -sSL https://raw.githubusercontent.com/aceisace/E-Paper-Calendar-with-iCal-sync-and-live-weather/master/2-Colour-support/setup | bash`**

Let me know if it works, thanks.

**Comment by aceisace** [comment]
I'll close this issue for now then.

**Comment by startedfromtheb0ttom** [comment]
Thank you! It's work's

**Comment by aceisace** [comment]
## Important Notice:
A kind note to anyone using the software, please update to the latest version (early October 2018) as it contains a critical update which prevents ghosting and damage to the display from over-voltage in the long-term. It also contains full support for the 2-Colour E-Paper version. Refer to the wiki for updating instructions.
